export { changeWhoPlay } from './changeWhoPlay.js'
export { campo } from './insert.js'
export { resetGame } from './resetGame.js'
export { playerLabel, sortPlayer } from './sortPlayer.js'
export { verifyAllFields } from '../resultsGame/verifyAllFields.js'
